name: Publish Website to CPanel

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP Deploy to cPanel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.linksfarmer.com
          username: linksfarmer
          password: £Xw3x%V87RQB
          server-dir: /public_html/       # <- Adjust based on your actual target folder
          local-dir: ./                   # <- Your Laravel root or `dist`, if it's a build
          protocol: ftp                   # or sftp
          port: 21                        # use 22 for SFTP
          timeout: 60000                 # optional: increase if needed
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/vendor/**
            **/storage/**
            .env
